CREATE DATABASE rastotInsight;

CREATE TABLE posts(
	id INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	user_id INT(11) NOT NULL,
	topic_id INT(11) NULL,
	post_title VARCHAR(255) UNIQUE,
	img_name VARCHAR(255),
	core TEXT,
	published TINYINT(2) NOT NULL,
	valid TINYINT(2) NOT NULL,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE `posts` ADD FOREIGN KEY (`user_id`)
REFERENCES `users`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE `posts` ADD FOREIGN KEY (`topic_id`) 
REFERENCES `topics`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

CREATE TABLE users(
	id INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	admin TINYINT(2),
	super_admin TINYINT(2),
	userName VARCHAR(127),
	email VARCHAR(127) UNIQUE,
	pass VARCHAR(127),
	verified TINYINT(1) NOT NULL,
	token VARCHAR(255) NOT NULL,
	reg_time DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE topics(
	id INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	title TEXT NOT NULL UNIQUE;
	description TEXT;
);

CREATE TABLE post_views(
	id INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	p_id INT(11) NULL;
	user_ip VARCHAR(255) NOT NULL;
);

ALTER TABLE `post_views` ADD FOREIGN KEY (`p_id`) 
REFERENCES `posts`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

CREATE TABLE view_counter(
	id INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	p_id INT(11) NULL;
	total_views INT(11);
);

ALTER TABLE `view_counter` ADD FOREIGN KEY (`p_id`) 
REFERENCES `posts`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;